name: Update Fixtures

on:
  schedule:
    - cron: '*/5 * * * *'  # 1 AM daily
  workflow_dispatch:

permissions:
  contents: write  # Needed to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Run script
        run: node app.js  # generates fixtures.json

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'daily-fixtures'
          name: 'daily-fixtures'
          body: 'Updated fixtures for today'
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload fixtures.json
        uses: softprops/action-gh-release@v1
        with:
          files: fixtures.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
