name: schedule
on:
  push:
    branches:
      - schedule
      - main
  schedule:
    - cron: '* * * * *'

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Download app.js from Gist
        run: |
          curl -o app.js https://gist.github.com/Abdelhamid-Zdh/5ad3981425655b311a53dcbb484afef6.js

      - name: Run script
        run: node app.js

      - name: Commit fixtures
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add fixtures.json
          git commit -m "Update fixtures"
          git push
