name: schedule
on:
  push:
    branches:
      - schedule
  schedule:
    - cron: '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Running
      run: |
        echo "Running!"
